// Code generated by ent, DO NOT EDIT.

package portfolio

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the portfolio type in the database.
	Label = "portfolio"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldJob holds the string denoting the job field in the database.
	FieldJob = "job"
	// FieldCareerYears holds the string denoting the career_years field in the database.
	FieldCareerYears = "career_years"
	// FieldTechStacks holds the string denoting the tech_stacks field in the database.
	FieldTechStacks = "tech_stacks"
	// FieldProjects holds the string denoting the projects field in the database.
	FieldProjects = "projects"
	// FieldPreferredCompany holds the string denoting the preferred_company field in the database.
	FieldPreferredCompany = "preferred_company"
	// Table holds the table name of the portfolio in the database.
	Table = "portfolios"
)

// Columns holds all SQL columns for portfolio fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldJob,
	FieldCareerYears,
	FieldTechStacks,
	FieldProjects,
	FieldPreferredCompany,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Portfolio queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByJob orders the results by the job field.
func ByJob(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJob, opts...).ToFunc()
}

// ByCareerYears orders the results by the career_years field.
func ByCareerYears(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCareerYears, opts...).ToFunc()
}

// ByPreferredCompany orders the results by the preferred_company field.
func ByPreferredCompany(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreferredCompany, opts...).ToFunc()
}
