// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Problem is the predicate function for problem builders.
type Problem func(*sql.Selector)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
