// Package gateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package gateway

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// AnalyzeCodeRequest Code to analyze
type AnalyzeCodeRequest struct {
	// Code Code to analyze
	Code string `json:"code"`

	// ProblemId ID of the problem
	ProblemId *string `json:"problem_id,omitempty"`
}

// AnalyzeResult Result of the analysis
type AnalyzeResult struct {
	// Points Points of the code
	Points int `json:"points"`

	// Strengths Strengths of the code
	Strengths []string `json:"strengths"`

	// Weaknesses Weaknesses of the code
	Weaknesses []string `json:"weaknesses"`
}

// Problem Problem
type Problem struct {
	// Factors Factors of the problem
	Factors []string `json:"factors"`

	// Id ID of the problem
	Id string `json:"id"`

	// Language Language of the problem
	Language string `json:"language"`
}

// AnalyzeCodeResponse Result of the analysis
type AnalyzeCodeResponse = AnalyzeResult

// CreateProblemResponse Problem
type CreateProblemResponse = Problem

// AnalyzeCodeJSONRequestBody defines body for AnalyzeCode for application/json ContentType.
type AnalyzeCodeJSONRequestBody = AnalyzeCodeRequest

// CreateProblemJSONRequestBody defines body for CreateProblem for application/json ContentType.
type CreateProblemJSONRequestBody = Problem

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AnalyzeCode request with any body
	AnalyzeCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AnalyzeCode(ctx context.Context, body AnalyzeCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProblem request with any body
	CreateProblemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateProblem(ctx context.Context, body CreateProblemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AnalyzeCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAnalyzeCodeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AnalyzeCode(ctx context.Context, body AnalyzeCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAnalyzeCodeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProblemWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProblemRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProblem(ctx context.Context, body CreateProblemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProblemRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAnalyzeCodeRequest calls the generic AnalyzeCode builder with application/json body
func NewAnalyzeCodeRequest(server string, body AnalyzeCodeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAnalyzeCodeRequestWithBody(server, "application/json", bodyReader)
}

// NewAnalyzeCodeRequestWithBody generates requests for AnalyzeCode with any type of body
func NewAnalyzeCodeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/analyze")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateProblemRequest calls the generic CreateProblem builder with application/json body
func NewCreateProblemRequest(server string, body CreateProblemJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateProblemRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateProblemRequestWithBody generates requests for CreateProblem with any type of body
func NewCreateProblemRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/problem")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AnalyzeCode request with any body
	AnalyzeCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnalyzeCodeResponse, error)

	AnalyzeCodeWithResponse(ctx context.Context, body AnalyzeCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*AnalyzeCodeResponse, error)

	// CreateProblem request with any body
	CreateProblemWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProblemResponse, error)

	CreateProblemWithResponse(ctx context.Context, body CreateProblemJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProblemResponse, error)
}

type AnalyzeCodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AnalyzeResult
}

// Status returns HTTPResponse.Status
func (r AnalyzeCodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AnalyzeCodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateProblemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Problem
}

// Status returns HTTPResponse.Status
func (r CreateProblemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateProblemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AnalyzeCodeWithBodyWithResponse request with arbitrary body returning *AnalyzeCodeResponse
func (c *ClientWithResponses) AnalyzeCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AnalyzeCodeResponse, error) {
	rsp, err := c.AnalyzeCodeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnalyzeCodeResponse(rsp)
}

func (c *ClientWithResponses) AnalyzeCodeWithResponse(ctx context.Context, body AnalyzeCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*AnalyzeCodeResponse, error) {
	rsp, err := c.AnalyzeCode(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAnalyzeCodeResponse(rsp)
}

// CreateProblemWithBodyWithResponse request with arbitrary body returning *CreateProblemResponse
func (c *ClientWithResponses) CreateProblemWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProblemResponse, error) {
	rsp, err := c.CreateProblemWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProblemResponse(rsp)
}

func (c *ClientWithResponses) CreateProblemWithResponse(ctx context.Context, body CreateProblemJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProblemResponse, error) {
	rsp, err := c.CreateProblem(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProblemResponse(rsp)
}

// ParseAnalyzeCodeResponse parses an HTTP response from a AnalyzeCodeWithResponse call
func ParseAnalyzeCodeResponse(rsp *http.Response) (*AnalyzeCodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AnalyzeCodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AnalyzeResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateProblemResponse parses an HTTP response from a CreateProblemWithResponse call
func ParseCreateProblemResponse(rsp *http.Response) (*CreateProblemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateProblemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Analyze code
	// (POST /analyze)
	AnalyzeCode(ctx echo.Context) error
	// Create a new problem
	// (POST /problem)
	CreateProblem(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// AnalyzeCode converts echo context to params.
func (w *ServerInterfaceWrapper) AnalyzeCode(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AnalyzeCode(ctx)
	return err
}

// CreateProblem converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProblem(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateProblem(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/analyze", wrapper.AnalyzeCode)
	router.POST(baseURL+"/problem", wrapper.CreateProblem)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWS2/bMAz+KwK3wwYYsdPHHr51HQYU2ICiO+zQFYNqM4k6W1Ipul1W+L8PshQnqd0H",
	"sPQW883vE8ncQWFqazRqdpDfAaGzRjvsPo60rJZ/8diUeBblXlwYzajZ/5TWVqqQrIxOr5zRXuaKBdbS",
	"/3pNOIMcXqXrHGnQujTGPkPXVAxt2yZQoitIWR8McvBZhQxWJbQJHBNKxlMylxXWO68nxh2rJKpE0RVQ",
	"greIbgOUrht0XSUjzbBZ9QMJWDIWiVVAujAlPscL/8jaVgg5lDgTM2PevM1/aiGEIOSGtJhCAry03sIx",
	"KT33yNnQwC9VDnOcfBZmJniBIlptZZnu7R8cvnv/4WM2jNsmQHjdKMIS8vPQQgKOJWPt6UjAGuWf1UXv",
	"ai6vsGBf0jb9g6qCfFVZ179TbgBbTDBwP+3kK/dYWd/VNMv6ipRmnCP5khwT6jkvRuJ9X6nuhVSMdWe+",
	"RuybVJql0vKy6s0GhESBJJJL/32L8rdGF8duO/ePXvciye+xuAZhq6pHuVyNzpCG/kVt0zaTBRsa6fVL",
	"UAxf5K6A3u0EJFBJPW/kfGR2v0bNY7HtkhdGPzlZqoSNTEkP35AL76n0zIyvkmOjNRYsjk5PfE7FXREb",
	"GkjgBskFj2wynWS+R2NRS6sgh/1JNvEwWBmnJF1tpm4Ww+LzRHcL+KSEfHM5QugKHX8y5XLXh2Rz/T50",
	"TbZW6RphpgY7yDdO316WPZS4t0vH7mObwEHwvffK9I2sVBleapvA4bgRI2lZCYd0gySQyFC4N01dS1qu",
	"EY2B2gRSu56/cRK2LucL0fCM+8kmntBnoD99Gv3x/wNP4b8C638oCJmFFBpv1wE7m87JQX5+Bw1VkMOC",
	"2bo8TaVVE09ZEUZtogy0F+2/AAAA//+hNO2RfwkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
