// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"portfolio/ent/predicate"
	"portfolio/ent/report"
	"portfolio/schema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ReportUpdate is the builder for updating Report entities.
type ReportUpdate struct {
	config
	hooks    []Hook
	mutation *ReportMutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (ru *ReportUpdate) Where(ps ...predicate.Report) *ReportUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetRequestID sets the "request_id" field.
func (ru *ReportUpdate) SetRequestID(s string) *ReportUpdate {
	ru.mutation.SetRequestID(s)
	return ru
}

// SetStatus sets the "status" field.
func (ru *ReportUpdate) SetStatus(s string) *ReportUpdate {
	ru.mutation.SetStatus(s)
	return ru
}

// SetProjectFeedbacks sets the "project_feedbacks" field.
func (ru *ReportUpdate) SetProjectFeedbacks(s []schema.Feedback) *ReportUpdate {
	ru.mutation.SetProjectFeedbacks(s)
	return ru
}

// AppendProjectFeedbacks appends s to the "project_feedbacks" field.
func (ru *ReportUpdate) AppendProjectFeedbacks(s []schema.Feedback) *ReportUpdate {
	ru.mutation.AppendProjectFeedbacks(s)
	return ru
}

// SetTechStackFeedbacks sets the "tech_stack_feedbacks" field.
func (ru *ReportUpdate) SetTechStackFeedbacks(s []schema.Feedback) *ReportUpdate {
	ru.mutation.SetTechStackFeedbacks(s)
	return ru
}

// AppendTechStackFeedbacks appends s to the "tech_stack_feedbacks" field.
func (ru *ReportUpdate) AppendTechStackFeedbacks(s []schema.Feedback) *ReportUpdate {
	ru.mutation.AppendTechStackFeedbacks(s)
	return ru
}

// SetProjectRecommendations sets the "project_recommendations" field.
func (ru *ReportUpdate) SetProjectRecommendations(s []schema.Recommendation) *ReportUpdate {
	ru.mutation.SetProjectRecommendations(s)
	return ru
}

// AppendProjectRecommendations appends s to the "project_recommendations" field.
func (ru *ReportUpdate) AppendProjectRecommendations(s []schema.Recommendation) *ReportUpdate {
	ru.mutation.AppendProjectRecommendations(s)
	return ru
}

// SetTechStackRecommendations sets the "tech_stack_recommendations" field.
func (ru *ReportUpdate) SetTechStackRecommendations(s []schema.Recommendation) *ReportUpdate {
	ru.mutation.SetTechStackRecommendations(s)
	return ru
}

// AppendTechStackRecommendations appends s to the "tech_stack_recommendations" field.
func (ru *ReportUpdate) AppendTechStackRecommendations(s []schema.Recommendation) *ReportUpdate {
	ru.mutation.AppendTechStackRecommendations(s)
	return ru
}

// Mutation returns the ReportMutation object of the builder.
func (ru *ReportUpdate) Mutation() *ReportMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *ReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *ReportUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *ReportUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *ReportUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *ReportUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.RequestID(); ok {
		_spec.SetField(report.FieldRequestID, field.TypeString, value)
	}
	if value, ok := ru.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
	}
	if value, ok := ru.mutation.ProjectFeedbacks(); ok {
		_spec.SetField(report.FieldProjectFeedbacks, field.TypeJSON, value)
	}
	if value, ok := ru.mutation.AppendedProjectFeedbacks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldProjectFeedbacks, value)
		})
	}
	if value, ok := ru.mutation.TechStackFeedbacks(); ok {
		_spec.SetField(report.FieldTechStackFeedbacks, field.TypeJSON, value)
	}
	if value, ok := ru.mutation.AppendedTechStackFeedbacks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldTechStackFeedbacks, value)
		})
	}
	if value, ok := ru.mutation.ProjectRecommendations(); ok {
		_spec.SetField(report.FieldProjectRecommendations, field.TypeJSON, value)
	}
	if value, ok := ru.mutation.AppendedProjectRecommendations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldProjectRecommendations, value)
		})
	}
	if value, ok := ru.mutation.TechStackRecommendations(); ok {
		_spec.SetField(report.FieldTechStackRecommendations, field.TypeJSON, value)
	}
	if value, ok := ru.mutation.AppendedTechStackRecommendations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldTechStackRecommendations, value)
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// ReportUpdateOne is the builder for updating a single Report entity.
type ReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportMutation
}

// SetRequestID sets the "request_id" field.
func (ruo *ReportUpdateOne) SetRequestID(s string) *ReportUpdateOne {
	ruo.mutation.SetRequestID(s)
	return ruo
}

// SetStatus sets the "status" field.
func (ruo *ReportUpdateOne) SetStatus(s string) *ReportUpdateOne {
	ruo.mutation.SetStatus(s)
	return ruo
}

// SetProjectFeedbacks sets the "project_feedbacks" field.
func (ruo *ReportUpdateOne) SetProjectFeedbacks(s []schema.Feedback) *ReportUpdateOne {
	ruo.mutation.SetProjectFeedbacks(s)
	return ruo
}

// AppendProjectFeedbacks appends s to the "project_feedbacks" field.
func (ruo *ReportUpdateOne) AppendProjectFeedbacks(s []schema.Feedback) *ReportUpdateOne {
	ruo.mutation.AppendProjectFeedbacks(s)
	return ruo
}

// SetTechStackFeedbacks sets the "tech_stack_feedbacks" field.
func (ruo *ReportUpdateOne) SetTechStackFeedbacks(s []schema.Feedback) *ReportUpdateOne {
	ruo.mutation.SetTechStackFeedbacks(s)
	return ruo
}

// AppendTechStackFeedbacks appends s to the "tech_stack_feedbacks" field.
func (ruo *ReportUpdateOne) AppendTechStackFeedbacks(s []schema.Feedback) *ReportUpdateOne {
	ruo.mutation.AppendTechStackFeedbacks(s)
	return ruo
}

// SetProjectRecommendations sets the "project_recommendations" field.
func (ruo *ReportUpdateOne) SetProjectRecommendations(s []schema.Recommendation) *ReportUpdateOne {
	ruo.mutation.SetProjectRecommendations(s)
	return ruo
}

// AppendProjectRecommendations appends s to the "project_recommendations" field.
func (ruo *ReportUpdateOne) AppendProjectRecommendations(s []schema.Recommendation) *ReportUpdateOne {
	ruo.mutation.AppendProjectRecommendations(s)
	return ruo
}

// SetTechStackRecommendations sets the "tech_stack_recommendations" field.
func (ruo *ReportUpdateOne) SetTechStackRecommendations(s []schema.Recommendation) *ReportUpdateOne {
	ruo.mutation.SetTechStackRecommendations(s)
	return ruo
}

// AppendTechStackRecommendations appends s to the "tech_stack_recommendations" field.
func (ruo *ReportUpdateOne) AppendTechStackRecommendations(s []schema.Recommendation) *ReportUpdateOne {
	ruo.mutation.AppendTechStackRecommendations(s)
	return ruo
}

// Mutation returns the ReportMutation object of the builder.
func (ruo *ReportUpdateOne) Mutation() *ReportMutation {
	return ruo.mutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (ruo *ReportUpdateOne) Where(ps ...predicate.Report) *ReportUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *ReportUpdateOne) Select(field string, fields ...string) *ReportUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Report entity.
func (ruo *ReportUpdateOne) Save(ctx context.Context) (*Report, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *ReportUpdateOne) SaveX(ctx context.Context) *Report {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *ReportUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *ReportUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *ReportUpdateOne) sqlSave(ctx context.Context) (_node *Report, err error) {
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Report.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, report.FieldID)
		for _, f := range fields {
			if !report.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != report.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.RequestID(); ok {
		_spec.SetField(report.FieldRequestID, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeString, value)
	}
	if value, ok := ruo.mutation.ProjectFeedbacks(); ok {
		_spec.SetField(report.FieldProjectFeedbacks, field.TypeJSON, value)
	}
	if value, ok := ruo.mutation.AppendedProjectFeedbacks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldProjectFeedbacks, value)
		})
	}
	if value, ok := ruo.mutation.TechStackFeedbacks(); ok {
		_spec.SetField(report.FieldTechStackFeedbacks, field.TypeJSON, value)
	}
	if value, ok := ruo.mutation.AppendedTechStackFeedbacks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldTechStackFeedbacks, value)
		})
	}
	if value, ok := ruo.mutation.ProjectRecommendations(); ok {
		_spec.SetField(report.FieldProjectRecommendations, field.TypeJSON, value)
	}
	if value, ok := ruo.mutation.AppendedProjectRecommendations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldProjectRecommendations, value)
		})
	}
	if value, ok := ruo.mutation.TechStackRecommendations(); ok {
		_spec.SetField(report.FieldTechStackRecommendations, field.TypeJSON, value)
	}
	if value, ok := ruo.mutation.AppendedTechStackRecommendations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, report.FieldTechStackRecommendations, value)
		})
	}
	_node = &Report{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
