// Code generated by ent, DO NOT EDIT.

package scenario

const (
	// Label holds the string label denoting the scenario type in the database.
	Label = "scenario"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// Table holds the table name of the scenario in the database.
	Table = "scenarios"
)

// Columns holds all SQL columns for scenario fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldTitle,
	FieldContent,
	FieldRequestID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
